import "@paperbits/core/ko/bindingHandlers/bindingHandlers.activate";
import "@paperbits/core/ko/bindingHandlers/bindingHandlers.component";
import "@paperbits/core/ko/bindingHandlers/bindingHandlers.focus";
import "@paperbits/core/ko/bindingHandlers/bindingHandlers.scrollable";
import "./bindingHandlers/acceptChange";
import "./bindingHandlers/copyToClipboard";
import "./bindingHandlers/markdown";
import "./bindingHandlers/scrollintoview";
import "./bindingHandlers/syntaxHighlight";
import { DefaultSettingsProvider } from "@paperbits/common/configuration";
import { DefaultEventManager } from "@paperbits/common/events";
import { XmlHttpRequestClient } from "@paperbits/common/http";
import { IInjector, IInjectorModule } from "@paperbits/common/injection";
import { ConsoleLogger } from "@paperbits/common/logging";
import { HistoryRouteHandler, LocationRouteHandler } from "@paperbits/common/routing";
import { ViewStack } from "@paperbits/common/ui/viewStack";
import { BalloonBindingHandler, ResizableBindingHandler } from "@paperbits/core/ko/bindingHandlers";
import { KnockoutRegistrationLoaders } from "@paperbits/core/ko/knockout.loaders";
import { DefaultSessionManager } from "./authentication/defaultSessionManager";
import { ApiDetails } from "./components/apis/details-of-api/ko/runtime/api-details";
import { ApiList, ApiListDropdown, ApiListTiles } from "./components/apis/list-of-apis/ko/runtime";
import { DefaultAuthenticator } from "./components/defaultAuthenticator";
import { FileInput } from "./components/file-input/file-input";
import { CodeSampleViewModel } from "./components/operations/operation-details/ko/runtime/code-sample";
import { OperationConsole } from "./components/operations/operation-details/ko/runtime/operation-console";
import { OperationDetails } from "./components/operations/operation-details/ko/runtime/operation-details";
// import { GraphqlConsole } from "./components/operations/operation-details/ko/runtime/graphql-console";
// import { GraphqlDocumentation } from "./components/operations/operation-details/ko/runtime/graphql-documentation/graphql-doc";
// import { GraphqlDetails } from "./components/operations/operation-details/ko/runtime/graphql-documentation/graphql-doc-details";
// import { GraphDocService } from "./components/operations/operation-details/ko/runtime/graphql-documentation/graphql-doc-service";
import { TypeDefinitionViewModel } from "./components/operations/operation-details/ko/runtime/type-definition";
import { OperationList } from "./components/operations/operation-list/ko/runtime/operation-list";
import { TagInput } from "./components/tag-input/tag-input";
import { ValidationSummary } from "./components/users/validation-summary/ko/runtime/validation-summary";
import { UnhandledErrorHandler } from "./errors/unhandledErrorHandler";
import "./polyfills";
import { RouteHelper } from "./routing/routeHelper";
import { StaticUserService } from "./services";
import { ApiService } from "./services/apiService";
import { TagService } from "./services/tagService";
import { Pagination } from "./components/pagination/pagination";
import { OauthServerConfiguration } from "./components/operations/operation-details/ko/runtime/oauth-server-configuration";

export class MainRuntimeModule implements IInjectorModule {
    public register(injector: IInjector): void {
        injector.bindSingleton("logger", ConsoleLogger);
        injector.bindModule(new KnockoutRegistrationLoaders());
        injector.bindSingleton("eventManager", DefaultEventManager);
        injector.bindToCollection("autostart", UnhandledErrorHandler);
        injector.bindToCollection("autostart", BalloonBindingHandler);
        injector.bindToCollection("autostart", ResizableBindingHandler);
        injector.bind("apiList", ApiList);
        injector.bind("apiListDropdown", ApiListDropdown);
        injector.bind("apiListTiles", ApiListTiles);
        injector.bind("apiDetails", ApiDetails);
        injector.bind("operationDetails", OperationDetails);
        injector.bind("operationConsole", OperationConsole);
        // injector.bind("graphqlConsole", GraphqlConsole);
        // injector.bind("graphqlDocumentation", GraphqlDocumentation);
        // injector.bind("graphqlDetails", GraphqlDetails);
        injector.bind("typeDefinition", TypeDefinitionViewModel);
        injector.bind("codeSample", CodeSampleViewModel);
        injector.bind("fileInput", FileInput);
        injector.bind("apiService", ApiService);
        injector.bind("tagService", TagService);
        injector.bind("validationSummary", ValidationSummary);
        injector.bind("operationList", OperationList);
        injector.bind("operationDetails", OperationDetails);
        injector.bindSingleton("httpClient", XmlHttpRequestClient);
        injector.bindSingleton("settingsProvider", DefaultSettingsProvider);
        injector.bindSingleton("authenticator", DefaultAuthenticator);
        injector.bindSingleton("routeHelper", RouteHelper);
        injector.bindSingleton("userService", StaticUserService);
        injector.bindSingleton("viewStack", ViewStack);
        injector.bindSingleton("sessionManager", DefaultSessionManager);
        injector.bind("tagInput", TagInput);
        // injector.bindSingleton("graphDocService", GraphDocService);
        // injector.bind("graphqlConsole", GraphqlConsole);
        // injector.bind("graphqlDocumentation", GraphqlDocumentation);
        // injector.bind("graphqlDetails", GraphqlDetails);
        injector.bind("pagination", Pagination);
        injector.bind("oauthServerConfiguration", OauthServerConfiguration);
        injector.bindToCollection("autostart", location.href.includes("designtime=true")
            ? HistoryRouteHandler
            : LocationRouteHandler);
    }
}